### ISSUE TITLE
"photish generate" encounter error

### ISSUE THREAD

**Issue by luckypoem** [henrylawson/photish#3]
hi.

root@AR:/usr/local/photish-site# photish generate
/usr/local/rvm/gems/ruby-2.3.0/gems/photish-0.7.6/lib/photish.rb:4:in `require': cannot load such file -- rake (LoadError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/photish-0.7.6/lib/photish.rb:4:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/photish-0.7.6/exe/photish:16:in `require'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/photish-0.7.6/exe/photish:16:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/photish:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/photish:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
root@AR:/usr/local/photish-site#

how to fix it?
tks

**Comment by luckypoem** [comment]
in another vps,also there is error:
root@localhost:/usr/local/photish-site# photish generate
/usr/local/rvm/gems/ruby-2.3.0/gems/photish-0.7.6/lib/photish.rb:4:in `require': cannot load such file -- rake (LoadError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/photish-0.7.6/lib/photish.rb:4:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/photish-0.7.6/exe/photish:16:in `require'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/photish-0.7.6/exe/photish:16:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/photish:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/photish:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
root@localhost:/usr/local/photish-site#
