### ISSUE TITLE
Error on photish generate

### ISSUE THREAD

**Issue by rfrankel** [henrylawson/photish#4]
I had the same Rake error as the other comment, but fixed that by making sure Rake was installed. 

However, after doing that I had a more serious problem (error trace below) 
It seems that Mini_magick has changed its interface slightly. 
Ah, bit rot...

photish generate
[2017-05-01T11:14:05.687][11601] DEBUG Photish::Command::Generate: Generating with 1 workers and 1 threads
[2017-05-01T11:14:05.688][11601] DEBUG Photish::Command::Worker: Worker #1 starting
[2017-05-01T11:14:05.688][11601] DEBUG Photish::Plugin::Repository: Loading plugins...
[2017-05-01T11:14:05.689][11601] DEBUG Photish::Plugin::Repository: Found plugin Photish::Plugin::TmpdirDeploy
[2017-05-01T11:14:05.689][11601] DEBUG Photish::Plugin::Repository: Found plugin Photish::Plugin::YellLoud
[2017-05-01T11:14:05.690][11601] DEBUG Photish::Plugin::Repository: Found plugin Photish::Plugin::FooterLinks
[2017-05-01T11:14:05.690][11601] DEBUG Photish::Plugin::Repository: Found plugin Photish::Plugin::Core::BuildUrl
[2017-05-01T11:14:05.690][11601] DEBUG Photish::Plugin::Repository: Found plugin Photish::Plugin::Core::Breadcrumb
[2017-05-01T11:14:05.690][11601] DEBUG Photish::Plugin::Repository: Found plugin Photish::Plugin::Core::Metadatable
[2017-05-01T11:14:05.690][11601] DEBUG Photish::Plugin::Repository: Found plugin Photish::Plugin::Core::Exifable
[2017-05-01T11:14:05.705][11601] DEBUG Photish::Render::GalleryPage: Rendering /big-dogs/custom-template-page/index.html to /home/rfrankel/www/photish_site/output/big-dogs/custom-template-page/index.html
[2017-05-01T11:14:05.715][11601] DEBUG Photish::Render::Template: Rendering /small-dogs/index.html with template /home/rfrankel/www/photish_site/site/_templates/album.slim to /home/rfrankel/www/photish_site/output/small-dogs/index.html
[2017-05-01T11:14:05.715][11601] DEBUG Photish::Render::Template: Rendering /small-dogs/fluffy-dogs/index.html with template /home/rfrankel/www/photish_site/site/_templates/album.slim to /home/rfrankel/www/photish_site/output/small-dogs/fluffy-dogs/index.html
[2017-05-01T11:14:05.716][11601] DEBUG Photish::Render::Template: Rendering /small-dogs/squishy-dogs/index.html with template /home/rfrankel/www/photish_site/site/_templates/album.slim to /home/rfrankel/www/photish_site/output/small-dogs/squishy-dogs/index.html
[2017-05-01T11:14:05.717][11601] DEBUG Photish::Render::Template: Rendering /big-dogs/index.html with template /home/rfrankel/www/photish_site/site/_templates/album.slim to /home/rfrankel/www/photish_site/output/big-dogs/index.html
[2017-05-01T11:14:05.724][11601] DEBUG Photish::Render::Template: Rendering /small-dogs/sleepy-dog/index.html with template /home/rfrankel/www/photish_site/site/_templates/photo.slim to /home/rfrankel/www/photish_site/output/small-dogs/sleepy-dog/index.html
[2017-05-01T11:14:05.725][11601] DEBUG Photish::Render::Template: Rendering /small-dogs/fluffy-dogs/exhausted-dogs/index.html with template /home/rfrankel/www/photish_site/site/_templates/photo.slim to /home/rfrankel/www/photish_site/output/small-dogs/fluffy-dogs/exhausted-dogs/index.html
[2017-05-01T11:14:05.725][11601] DEBUG Photish::Render::Template: Rendering /small-dogs/fluffy-dogs/many-dogs/index.html with template /home/rfrankel/www/photish_site/site/_templates/photo.slim to /home/rfrankel/www/photish_site/output/small-dogs/fluffy-dogs/many-dogs/index.html
[2017-05-01T11:14:05.726][11601] DEBUG Photish::Render::Template: Rendering /small-dogs/squishy-dogs/big-ear-dog/index.html with template /home/rfrankel/www/photish_site/site/_templates/photo.slim to /home/rfrankel/www/photish_site/output/small-dogs/squishy-dogs/big-ear-dog/index.html
[2017-05-01T11:14:05.726][11601] DEBUG Photish::Render::Template: Rendering /big-dogs/winking-dog/index.html with template /home/rfrankel/www/photish_site/site/_templates/photo.slim to /home/rfrankel/www/photish_site/output/big-dogs/winking-dog/index.html
[2017-05-01T11:14:05.727][11601] DEBUG Photish::Render::Template: Rendering /big-dogs/tired-dogs/index.html with template /home/rfrankel/www/photish_site/site/_templates/photo.slim to /home/rfrankel/www/photish_site/output/big-dogs/tired-dogs/index.html
[2017-05-01T11:14:05.727][11601] DEBUG Photish::Render::Image: Rendering 12 images across 1 threads
MiniMagick.debug is deprecated and will be removed in MiniMagick 5. Use `MiniMagick.logger.level = Logger::DEBUG` instead.
[2017-05-01T11:14:05.728][11601] FATAL Photish::Command::Worker: Photish::Command::Worker died due to NameError
[2017-05-01T11:14:05.730][11601] FATAL Photish::Command::Worker: NameError "uninitialized constant MiniMagick::Logger
Did you mean?  Logger"
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/render/image.rb:119:in `block in setup_minimagick'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/mini_magick-4.7.0/lib/mini_magick/configuration.rb:102:in `configure'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/render/image.rb:115:in `setup_minimagick'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/render/image.rb:14:in `render'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/render/gallery.rb:29:in `block in tasks'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/render/gallery.rb:10:in `each'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/render/gallery.rb:10:in `all_for'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/command/worker.rb:26:in `render_whole_site'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/command/worker.rb:8:in `run'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/command/base.rb:14:in `block in execute'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/log/safe_block.rb:6:in `handle_errors'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/command/base.rb:13:in `execute'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/command/generate.rb:53:in `single_worker'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/command/generate.rb:35:in `spawn_all_workers'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/command/generate.rb:8:in `run'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/command/base.rb:14:in `block in execute'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/log/safe_block.rb:6:in `handle_errors'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/command/base.rb:13:in `execute'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/lib/photish/cli/interface.rb:22:in `generate'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/home/rfrankel/.rvm/gems/ruby-2.4.0/gems/photish-0.7.6/exe/photish:17:in `<top (required)>'
/home/rfrankel/.rvm/gems/ruby-2.4.0/bin/photish:22:in `load'
/home/rfrankel/.rvm/gems/ruby-2.4.0/bin/photish:22:in `<main>'
/home/rfrankel/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/rfrankel/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
[2017-05-01T11:14:05.730][11601] FATAL Photish::Command::Generate: Photish::Command::Generate died due to SystemExit
rfrankel@affection:~/www/photish_site$

**Comment by tgerczei** [comment]
will work with mini_magick version 4.4.0
